[build]
publish = "public"
#command = "npm run build && npm run ipfs-deploy"

[context.production.environment]
HUGO_VERSION = "0.60.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://huangdiv.netlify.com/*"
  to = "https://huangdiv.com/:splat"
  force = true